"""Data loading: a synthetic GARCH(1,1)-like OHLC generator and a real loader.

The DEFAULT, key-free data path is a deterministic, seeded GARCH(1,1)-like
volatility-clustering generator that emits a full OHLC frame, so range-based RV
(Parkinson / Garman-Klass) is computable. Because the data IS generated by a
GARCH process, GARCH is the true model and ML cannot reliably beat it — the
honest null holds BY CONSTRUCTION on the default run.

The real loader (:func:`get_ohlc`) prefers the Polygon provider (lazy import) and
degrades gracefully to the synthetic generator, reporting provenance via
``DataSource`` so the API's ``data_source`` field is honest. The heavy data
dependencies live behind the ``[data]`` extra and are imported lazily inside
these functions. Importing this module has no side effects.
"""

from __future__ import annotations

from datetime import date
from typing import Literal

import numpy as np
import pandas as pd

from volforecast._exceptions import ValidationError
from volforecast._rng import make_rng
from volforecast._validation import ensure_series

#: Where an OHLC panel ultimately came from (reported to the API caller).
DataSource = Literal["polygon", "synthetic"]

#: The canonical OHLC column order produced and consumed across the library.
OHLC_COLUMNS: tuple[str, ...] = ("open", "high", "low", "close")

#: A fixed anchor date for the synthetic index (a Monday) so the default,
#: key-free run is byte-reproducible across machines and never depends on the
#: wall clock.
_DEFAULT_START: date = date(2016, 1, 4)

# quantcore-candidate: synthetic generator mirrors risk-metrics:data.py (seeded,
# offline-safe) but emits OHLC with GARCH(1,1) volatility clustering.


def generate_garch_ohlc(
    *,
    n_obs: int = 1500,
    omega: float = 2.0e-6,
    alpha: float = 0.08,
    beta: float = 0.90,
    mu: float = 0.0,
    seed: int = 7,
    start: date | None = None,
    intraday_range_scale: float = 1.0,
) -> pd.DataFrame:
    r"""Generate a deterministic GARCH(1,1)-like OHLC frame (the honest-null default).

    Simulates daily log returns from a Gaussian GARCH(1,1) process

    .. math::

        r_t = \mu + \sigma_t \varepsilon_t, \quad
        \sigma^2_t = \omega + \alpha\, r_{t-1}^2 + \beta\, \sigma^2_{t-1},
        \quad \varepsilon_t \sim \mathcal{N}(0, 1),

    accumulates a close-price path, and synthesizes a coherent OHLC bar per day
    (intraday high/low drawn around the open/close consistent with the day's
    conditional volatility, scaled by ``intraday_range_scale``) so Parkinson /
    Garman-Klass RV is well-defined. Stationarity requires ``alpha + beta < 1``.

    DETERMINISM: all randomness flows from :func:`volforecast._rng.make_rng`
    seeded by ``seed`` and the same arguments always yield a byte-identical frame.

    Parameters
    ----------
    n_obs:
        Number of daily bars to generate (``>= 2``).
    omega, alpha, beta:
        GARCH(1,1) parameters; require ``omega > 0``, ``alpha >= 0``,
        ``beta >= 0``, and (for stationarity) ``alpha + beta < 1``.
    mu:
        The daily mean log return.
    seed:
        Master RNG seed.
    start:
        First business day of the index (defaults to a fixed anchor date).
    intraday_range_scale:
        Multiplies the simulated high-low range (``> 0``); ``1.0`` is the
        calibrated default.

    Returns
    -------
    pandas.DataFrame
        An OHLC frame (columns :data:`OHLC_COLUMNS`) on a business-day index,
        with strictly positive prices and ``high >= max(open, close) >= ... >=
        low``.

    Raises
    ------
    ValidationError
        If ``n_obs < 2``, a parameter is out of domain, or ``alpha + beta >= 1``.
    """
    if not isinstance(n_obs, int) or isinstance(n_obs, bool):
        raise ValidationError(f"n_obs must be an int, got {type(n_obs).__name__}.")
    if n_obs < 2:
        raise ValidationError(f"n_obs must be >= 2, got {n_obs}.")
    for label, value in (("omega", omega), ("alpha", alpha), ("beta", beta), ("mu", mu)):
        if not np.isfinite(value):
            raise ValidationError(f"{label} must be finite, got {value!r}.")
    if omega <= 0.0:
        raise ValidationError(f"omega must be > 0, got {omega}.")
    if alpha < 0.0:
        raise ValidationError(f"alpha must be >= 0, got {alpha}.")
    if beta < 0.0:
        raise ValidationError(f"beta must be >= 0, got {beta}.")
    if alpha + beta >= 1.0:
        raise ValidationError(f"alpha + beta must be < 1 for stationarity, got {alpha + beta}.")
    if not (np.isfinite(intraday_range_scale) and intraday_range_scale > 0.0):
        raise ValidationError(
            f"intraday_range_scale must be a positive finite float, got {intraday_range_scale!r}."
        )

    gen = make_rng(seed)

    # --- Simulate the GARCH(1,1) log-return path -------------------------- #
    # All draws come from the single seeded generator so that an identical
    # ``(n_obs, omega, alpha, beta, mu, seed, intraday_range_scale)`` always
    # yields a byte-identical frame (pinned by a determinism test).
    eps = gen.standard_normal(n_obs)
    sigma2 = np.empty(n_obs, dtype="float64")
    returns = np.empty(n_obs, dtype="float64")
    # Seed the variance recursion at the unconditional variance so there is no
    # warm-up transient: ``omega / (1 - alpha - beta)``.
    sigma2[0] = omega / (1.0 - alpha - beta)
    returns[0] = mu + np.sqrt(sigma2[0]) * eps[0]
    for t in range(1, n_obs):
        sigma2[t] = omega + alpha * (returns[t - 1] - mu) ** 2 + beta * sigma2[t - 1]
        returns[t] = mu + np.sqrt(sigma2[t]) * eps[t]
    sigma = np.sqrt(sigma2)

    # --- Build a coherent OHLC bar per day -------------------------------- #
    close = 100.0 * np.exp(np.cumsum(returns))
    prev_close = np.empty(n_obs, dtype="float64")
    prev_close[0] = 100.0
    prev_close[1:] = close[:-1]
    # Open near the previous close with a small overnight gap proportional to
    # the day's conditional volatility.
    open_ = prev_close * np.exp(0.25 * sigma * gen.standard_normal(n_obs))

    body_high = np.maximum(open_, close)
    body_low = np.minimum(open_, close)
    # Intraday excursions are non-negative (|N(0,1)|) and scaled by the day's
    # conditional vol, so the high sits at or above the body top and the low at
    # or below the body bottom by construction.
    up = np.abs(gen.standard_normal(n_obs)) * sigma * float(intraday_range_scale)
    down = np.abs(gen.standard_normal(n_obs)) * sigma * float(intraday_range_scale)
    high = body_high * np.exp(up)
    low = body_low * np.exp(-down)

    index = pd.bdate_range(start=start if start is not None else _DEFAULT_START, periods=n_obs)
    frame = pd.DataFrame(
        {"open": open_, "high": high, "low": low, "close": close},
        index=index,
    ).astype("float64")
    return frame[list(OHLC_COLUMNS)]


def get_ohlc(
    ticker: str,
    start: date,
    end: date,
    *,
    source_pref: Literal["polygon", "synthetic", "auto"] = "auto",
    seed: int = 7,
) -> tuple[pd.DataFrame, DataSource]:
    """Fetch a daily OHLC frame for one ticker, degrading to synthetic.

    Resolution: with ``source_pref="polygon"`` (or ``"auto"``) the real Polygon
    EOD provider is tried first (lazy import) and, on any failure or absent key,
    falls through to the deterministic :func:`generate_garch_ohlc`. With
    ``source_pref="synthetic"`` it goes straight to the generator. The returned
    ``DataSource`` reports what actually produced the data.

    LAZY IMPORT: the Polygon provider (and ``httpx``) are imported inside this
    function, never at module import time.

    Parameters
    ----------
    ticker:
        The symbol to fetch (e.g. ``"SPY"``).
    start, end:
        Inclusive date range.
    source_pref:
        ``"auto"``/``"polygon"`` try Polygon then synthetic; ``"synthetic"``
        forces the generator.
    seed:
        Seed for the synthetic fallback (so the default run is reproducible).

    Returns
    -------
    tuple[pandas.DataFrame, DataSource]
        The OHLC frame (columns :data:`OHLC_COLUMNS`) and its provenance.

    Raises
    ------
    ValidationError
        If ``ticker`` is empty or ``end <= start``.
    """
    if not isinstance(ticker, str) or not ticker.strip():
        raise ValidationError("ticker must be a non-empty string.")
    if not isinstance(start, date) or not isinstance(end, date):
        raise ValidationError("start and end must be datetime.date instances.")
    if end <= start:
        raise ValidationError(f"end ({end}) must be strictly after start ({start}).")
    if source_pref not in ("polygon", "synthetic", "auto"):
        raise ValidationError(
            f"source_pref must be 'polygon', 'synthetic', or 'auto', got {source_pref!r}."
        )

    # Approximate the number of trading days in the requested window (~252 / yr)
    # so the synthetic fallback emits a series of a plausible length.
    span_days = (end - start).days
    n_obs = max(2, round(span_days * 252.0 / 365.25))

    if source_pref != "synthetic":
        polygon = _try_polygon(ticker, start, end)
        if polygon is not None:
            return polygon, "polygon"

    frame = generate_garch_ohlc(n_obs=n_obs, seed=seed, start=start)
    return frame, "synthetic"


def _try_polygon(ticker: str, start: date, end: date) -> pd.DataFrame | None:
    """Attempt to fetch daily OHLC from Polygon, returning ``None`` on any failure.

    LAZY IMPORT: the Polygon provider (and ``httpx``) live behind the ``[data]``
    extra and are imported INSIDE this function, never at module import time, so
    ``import volforecast`` never pulls in a network client. The default, key-free
    environment has no provider module / no API key, so this returns ``None`` and
    the caller degrades to the synthetic generator — the offline path is the
    common case.
    """
    try:  # pragma: no cover - exercised only when a real provider is installed
        from volforecast._providers.polygon import fetch_ohlc  # type: ignore[import-not-found]
    except ImportError:
        return None

    try:  # pragma: no cover - network path, not exercised in the offline suite
        frame = fetch_ohlc(ticker, start, end)
    except Exception:  # any provider failure degrades to synthetic
        return None

    if not isinstance(frame, pd.DataFrame) or frame.empty:  # pragma: no cover
        return None
    return frame


def log_returns(close: pd.Series) -> pd.Series:
    r"""Convert a close-price series to daily log returns (no-lookahead).

    NO-LOOKAHEAD REQUIREMENT: uses ``numpy.log(close).diff()`` with NO prior
    forward-fill — ffill-then-diff manufactures spurious zero returns across gaps
    and leaks information. The leading NaN row is dropped.

    Parameters
    ----------
    close:
        A 1-D close-price series indexed by date (strictly positive).

    Returns
    -------
    pandas.Series
        The daily log-return series with the leading NaN removed.

    Raises
    ------
    ValidationError
        If ``close`` is empty or contains non-positive prices.
    """
    prices = ensure_series(close, name="close", allow_nan=True)
    finite = prices.dropna()
    if not finite.empty and not bool((finite.to_numpy() > 0.0).all()):
        raise ValidationError("close contains non-positive prices.")

    # NO-LOOKAHEAD: log-then-diff with NO prior ffill. Forward-filling before the
    # diff would manufacture spurious zero returns across gaps (leaking the
    # "no change" information backward); the leading NaN from ``.diff()`` is the
    # only row dropped.
    log_prices = pd.Series(np.log(prices.to_numpy(dtype="float64")), index=prices.index)
    returns = log_prices.diff().dropna()
    return pd.Series(returns, index=returns.index, name="log_return", dtype="float64")
