"""Data loading: a synthetic GARCH(1,1)-like OHLC generator and a real loader.

The DEFAULT, key-free data path is a deterministic, seeded GARCH(1,1)-like
volatility-clustering generator that emits a full OHLC frame, so range-based RV
(Parkinson / Garman-Klass) is computable. Because the data IS generated by a
GARCH process, GARCH is the true model and ML cannot reliably beat it — the
honest null holds BY CONSTRUCTION on the default run.

The real loader (:func:`get_ohlc`) prefers the Polygon provider (lazy import) and
degrades gracefully to the synthetic generator, reporting provenance via
``DataSource`` so the API's ``data_source`` field is honest. The heavy data
dependencies live behind the ``[data]`` extra and are imported lazily inside
these functions. Importing this module has no side effects.
"""

from __future__ import annotations

from datetime import date
from typing import Literal

import pandas as pd

#: Where an OHLC panel ultimately came from (reported to the API caller).
DataSource = Literal["polygon", "synthetic"]

#: The canonical OHLC column order produced and consumed across the library.
OHLC_COLUMNS: tuple[str, ...] = ("open", "high", "low", "close")

# quantcore-candidate: synthetic generator mirrors risk-metrics:data.py (seeded,
# offline-safe) but emits OHLC with GARCH(1,1) volatility clustering.


def generate_garch_ohlc(
    *,
    n_obs: int = 1500,
    omega: float = 2.0e-6,
    alpha: float = 0.08,
    beta: float = 0.90,
    mu: float = 0.0,
    seed: int = 7,
    start: date | None = None,
    intraday_range_scale: float = 1.0,
) -> pd.DataFrame:
    r"""Generate a deterministic GARCH(1,1)-like OHLC frame (the honest-null default).

    Simulates daily log returns from a Gaussian GARCH(1,1) process

    .. math::

        r_t = \mu + \sigma_t \varepsilon_t, \quad
        \sigma^2_t = \omega + \alpha\, r_{t-1}^2 + \beta\, \sigma^2_{t-1},
        \quad \varepsilon_t \sim \mathcal{N}(0, 1),

    accumulates a close-price path, and synthesizes a coherent OHLC bar per day
    (intraday high/low drawn around the open/close consistent with the day's
    conditional volatility, scaled by ``intraday_range_scale``) so Parkinson /
    Garman-Klass RV is well-defined. Stationarity requires ``alpha + beta < 1``.

    DETERMINISM: all randomness flows from :func:`volforecast._rng.make_rng`
    seeded by ``seed`` and the same arguments always yield a byte-identical frame.

    Parameters
    ----------
    n_obs:
        Number of daily bars to generate (``>= 2``).
    omega, alpha, beta:
        GARCH(1,1) parameters; require ``omega > 0``, ``alpha >= 0``,
        ``beta >= 0``, and (for stationarity) ``alpha + beta < 1``.
    mu:
        The daily mean log return.
    seed:
        Master RNG seed.
    start:
        First business day of the index (defaults to a fixed anchor date).
    intraday_range_scale:
        Multiplies the simulated high-low range (``> 0``); ``1.0`` is the
        calibrated default.

    Returns
    -------
    pandas.DataFrame
        An OHLC frame (columns :data:`OHLC_COLUMNS`) on a business-day index,
        with strictly positive prices and ``high >= max(open, close) >= ... >=
        low``.

    Raises
    ------
    ValidationError
        If ``n_obs < 2``, a parameter is out of domain, or ``alpha + beta >= 1``.
    """
    raise NotImplementedError


def get_ohlc(
    ticker: str,
    start: date,
    end: date,
    *,
    source_pref: Literal["polygon", "synthetic", "auto"] = "auto",
    seed: int = 7,
) -> tuple[pd.DataFrame, DataSource]:
    """Fetch a daily OHLC frame for one ticker, degrading to synthetic.

    Resolution: with ``source_pref="polygon"`` (or ``"auto"``) the real Polygon
    EOD provider is tried first (lazy import) and, on any failure or absent key,
    falls through to the deterministic :func:`generate_garch_ohlc`. With
    ``source_pref="synthetic"`` it goes straight to the generator. The returned
    ``DataSource`` reports what actually produced the data.

    LAZY IMPORT: the Polygon provider (and ``httpx``) are imported inside this
    function, never at module import time.

    Parameters
    ----------
    ticker:
        The symbol to fetch (e.g. ``"SPY"``).
    start, end:
        Inclusive date range.
    source_pref:
        ``"auto"``/``"polygon"`` try Polygon then synthetic; ``"synthetic"``
        forces the generator.
    seed:
        Seed for the synthetic fallback (so the default run is reproducible).

    Returns
    -------
    tuple[pandas.DataFrame, DataSource]
        The OHLC frame (columns :data:`OHLC_COLUMNS`) and its provenance.

    Raises
    ------
    ValidationError
        If ``ticker`` is empty or ``end <= start``.
    """
    raise NotImplementedError


def log_returns(close: pd.Series) -> pd.Series:
    r"""Convert a close-price series to daily log returns (no-lookahead).

    NO-LOOKAHEAD REQUIREMENT: uses ``numpy.log(close).diff()`` with NO prior
    forward-fill — ffill-then-diff manufactures spurious zero returns across gaps
    and leaks information. The leading NaN row is dropped.

    Parameters
    ----------
    close:
        A 1-D close-price series indexed by date (strictly positive).

    Returns
    -------
    pandas.Series
        The daily log-return series with the leading NaN removed.

    Raises
    ------
    ValidationError
        If ``close`` is empty or contains non-positive prices.
    """
    raise NotImplementedError
